Repository swig/swig, pull requests merged in 2022-04, with the labels that each got.

#2252 Remove bogus parser grammar rule for unary &&
  Source/CParse/parser.y
Labels: C++11

#2258 Fix Ruby 3.2 warning "undefining the allocator of T_DATA class swig_runtime_data"
  Lib/ruby/rubyrun.swg
Labels: Ruby

#2241 [Go] Add missing newlines for goin typemaps
  CHANGES.current
  Examples/go/check.list
  Examples/go/goin/Makefile
  Examples/go/goin/example.i
  Examples/go/goin/index.html
  Examples/go/goin/runme.go
  Examples/go/index.html
  Examples/test-suite/go/go_director_inout_runme.go
  Examples/test-suite/go_director_inout.i
  Source/Modules/go.cxx
Labels: Go
